version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn
      - run: yarn run test
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules
      - store_test_results:
          path: ~/app/junit.xml

  android:
    working_directory: ~/app
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run: bundle install
      - run: bundle exec fastlane test
      - store_test_results:
          path: ~/project/android/reports

workflows:
  version: 2
  node-android-ios:
    jobs:
      - build
      - android:
          requires:
            - build