# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.67.0"

default_platform(:android)

lane :build do |options|
    schema = options[:release] ? "Release" : "Debug"
      gradle(task: 'assemble', build_type: schema)
end

lane :send_fail_message do
    slack(
      message: 'Build failed',
      success: false,
      slack_url: 'https://hooks.slack.com/services/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',
      channel: '#build'
    )
end